/*
Sumo Logic Organizations Management API

Welcome to the Sumo Logic's API Reference for Organizations Management. You can use these APIs to interact with the Sumo Logic platform to manage accounts and subscription. Refer to [API Authentication](https://help.sumologic.com/APIs/General-API-Information/API-Authentication) for more information about authentication. You can also look at [other APIs](https://help.sumologic.com/APIs) for more information about some other API endpoints. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DetailedUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DetailedUsage{}

// DetailedUsage struct for DetailedUsage
type DetailedUsage struct {
	// Denotes the total number of credits provisioned for the child organization to use.
	TotalCapacity float64 `json:"totalCapacity"`
	// Denotes the total number of credits that have been utilized.
	TotalCreditsUsed float64 `json:"totalCreditsUsed"`
	// The amount of credits used by the organization in form of deployment charge.
	DeploymentChargeCreditsUsed float64 `json:"deploymentChargeCreditsUsed"`
	// The amount of credits used by the organization excluding deployment charge.
	AllocatedCreditsUsed float64 `json:"allocatedCreditsUsed"`
	// Contains details of the credits used per product variable.
	Usages []UsagePerProductVariable `json:"usages"`
}

type _DetailedUsage DetailedUsage

// NewDetailedUsage instantiates a new DetailedUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDetailedUsage(totalCapacity float64, totalCreditsUsed float64, deploymentChargeCreditsUsed float64, allocatedCreditsUsed float64, usages []UsagePerProductVariable) *DetailedUsage {
	this := DetailedUsage{}
	this.TotalCapacity = totalCapacity
	this.TotalCreditsUsed = totalCreditsUsed
	this.DeploymentChargeCreditsUsed = deploymentChargeCreditsUsed
	this.AllocatedCreditsUsed = allocatedCreditsUsed
	this.Usages = usages
	return &this
}

// NewDetailedUsageWithDefaults instantiates a new DetailedUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDetailedUsageWithDefaults() *DetailedUsage {
	this := DetailedUsage{}
	return &this
}

// GetTotalCapacity returns the TotalCapacity field value
func (o *DetailedUsage) GetTotalCapacity() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.TotalCapacity
}

// GetTotalCapacityOk returns a tuple with the TotalCapacity field value
// and a boolean to check if the value has been set.
func (o *DetailedUsage) GetTotalCapacityOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCapacity, true
}

// SetTotalCapacity sets field value
func (o *DetailedUsage) SetTotalCapacity(v float64) {
	o.TotalCapacity = v
}

// GetTotalCreditsUsed returns the TotalCreditsUsed field value
func (o *DetailedUsage) GetTotalCreditsUsed() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.TotalCreditsUsed
}

// GetTotalCreditsUsedOk returns a tuple with the TotalCreditsUsed field value
// and a boolean to check if the value has been set.
func (o *DetailedUsage) GetTotalCreditsUsedOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCreditsUsed, true
}

// SetTotalCreditsUsed sets field value
func (o *DetailedUsage) SetTotalCreditsUsed(v float64) {
	o.TotalCreditsUsed = v
}

// GetDeploymentChargeCreditsUsed returns the DeploymentChargeCreditsUsed field value
func (o *DetailedUsage) GetDeploymentChargeCreditsUsed() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.DeploymentChargeCreditsUsed
}

// GetDeploymentChargeCreditsUsedOk returns a tuple with the DeploymentChargeCreditsUsed field value
// and a boolean to check if the value has been set.
func (o *DetailedUsage) GetDeploymentChargeCreditsUsedOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeploymentChargeCreditsUsed, true
}

// SetDeploymentChargeCreditsUsed sets field value
func (o *DetailedUsage) SetDeploymentChargeCreditsUsed(v float64) {
	o.DeploymentChargeCreditsUsed = v
}

// GetAllocatedCreditsUsed returns the AllocatedCreditsUsed field value
func (o *DetailedUsage) GetAllocatedCreditsUsed() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.AllocatedCreditsUsed
}

// GetAllocatedCreditsUsedOk returns a tuple with the AllocatedCreditsUsed field value
// and a boolean to check if the value has been set.
func (o *DetailedUsage) GetAllocatedCreditsUsedOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AllocatedCreditsUsed, true
}

// SetAllocatedCreditsUsed sets field value
func (o *DetailedUsage) SetAllocatedCreditsUsed(v float64) {
	o.AllocatedCreditsUsed = v
}

// GetUsages returns the Usages field value
func (o *DetailedUsage) GetUsages() []UsagePerProductVariable {
	if o == nil {
		var ret []UsagePerProductVariable
		return ret
	}

	return o.Usages
}

// GetUsagesOk returns a tuple with the Usages field value
// and a boolean to check if the value has been set.
func (o *DetailedUsage) GetUsagesOk() ([]UsagePerProductVariable, bool) {
	if o == nil {
		return nil, false
	}
	return o.Usages, true
}

// SetUsages sets field value
func (o *DetailedUsage) SetUsages(v []UsagePerProductVariable) {
	o.Usages = v
}

func (o DetailedUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DetailedUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["totalCapacity"] = o.TotalCapacity
	toSerialize["totalCreditsUsed"] = o.TotalCreditsUsed
	toSerialize["deploymentChargeCreditsUsed"] = o.DeploymentChargeCreditsUsed
	toSerialize["allocatedCreditsUsed"] = o.AllocatedCreditsUsed
	toSerialize["usages"] = o.Usages
	return toSerialize, nil
}

func (o *DetailedUsage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"totalCapacity",
		"totalCreditsUsed",
		"deploymentChargeCreditsUsed",
		"allocatedCreditsUsed",
		"usages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDetailedUsage := _DetailedUsage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDetailedUsage)

	if err != nil {
		return err
	}

	*o = DetailedUsage(varDetailedUsage)

	return err
}

type NullableDetailedUsage struct {
	value *DetailedUsage
	isSet bool
}

func (v NullableDetailedUsage) Get() *DetailedUsage {
	return v.value
}

func (v *NullableDetailedUsage) Set(val *DetailedUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableDetailedUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableDetailedUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDetailedUsage(val *DetailedUsage) *NullableDetailedUsage {
	return &NullableDetailedUsage{value: val, isSet: true}
}

func (v NullableDetailedUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDetailedUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


