/*
Sumo Logic Organizations Management API

Welcome to the Sumo Logic's API Reference for Organizations Management. You can use these APIs to interact with the Sumo Logic platform to manage accounts and subscription. Refer to [API Authentication](https://help.sumologic.com/APIs/General-API-Information/API-Authentication) for more information about authentication. You can also look at [other APIs](https://help.sumologic.com/APIs) for more information about some other API endpoints. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Usage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Usage{}

// Usage struct for Usage
type Usage struct {
	// Denotes the total number of credits provisioned for the child organization to use.
	TotalCapacity float64 `json:"totalCapacity"`
	// Denotes the total number of credits that have been utilized.
	TotalCreditsUsed float64 `json:"totalCreditsUsed"`
}

type _Usage Usage

// NewUsage instantiates a new Usage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsage(totalCapacity float64, totalCreditsUsed float64) *Usage {
	this := Usage{}
	this.TotalCapacity = totalCapacity
	this.TotalCreditsUsed = totalCreditsUsed
	return &this
}

// NewUsageWithDefaults instantiates a new Usage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageWithDefaults() *Usage {
	this := Usage{}
	return &this
}

// GetTotalCapacity returns the TotalCapacity field value
func (o *Usage) GetTotalCapacity() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.TotalCapacity
}

// GetTotalCapacityOk returns a tuple with the TotalCapacity field value
// and a boolean to check if the value has been set.
func (o *Usage) GetTotalCapacityOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCapacity, true
}

// SetTotalCapacity sets field value
func (o *Usage) SetTotalCapacity(v float64) {
	o.TotalCapacity = v
}

// GetTotalCreditsUsed returns the TotalCreditsUsed field value
func (o *Usage) GetTotalCreditsUsed() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.TotalCreditsUsed
}

// GetTotalCreditsUsedOk returns a tuple with the TotalCreditsUsed field value
// and a boolean to check if the value has been set.
func (o *Usage) GetTotalCreditsUsedOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCreditsUsed, true
}

// SetTotalCreditsUsed sets field value
func (o *Usage) SetTotalCreditsUsed(v float64) {
	o.TotalCreditsUsed = v
}

func (o Usage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Usage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["totalCapacity"] = o.TotalCapacity
	toSerialize["totalCreditsUsed"] = o.TotalCreditsUsed
	return toSerialize, nil
}

func (o *Usage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"totalCapacity",
		"totalCreditsUsed",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsage := _Usage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsage)

	if err != nil {
		return err
	}

	*o = Usage(varUsage)

	return err
}

type NullableUsage struct {
	value *Usage
	isSet bool
}

func (v NullableUsage) Get() *Usage {
	return v.value
}

func (v *NullableUsage) Set(val *Usage) {
	v.value = val
	v.isSet = true
}

func (v NullableUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsage(val *Usage) *NullableUsage {
	return &NullableUsage{value: val, isSet: true}
}

func (v NullableUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


