/*
Sumo Logic Organizations Management API

Welcome to the Sumo Logic's API Reference for Organizations Management. You can use these APIs to interact with the Sumo Logic platform to manage accounts and subscription. Refer to [API Authentication](https://help.sumologic.com/APIs/General-API-Information/API-Authentication) for more information about authentication. You can also look at [other APIs](https://help.sumologic.com/APIs) for more information about some other API endpoints. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DelinkChildOrgsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DelinkChildOrgsRequest{}

// DelinkChildOrgsRequest struct for DelinkChildOrgsRequest
type DelinkChildOrgsRequest struct {
	// A list of identifiers for the child organizations.
	OrgIds []string `json:"orgIds"`
}

type _DelinkChildOrgsRequest DelinkChildOrgsRequest

// NewDelinkChildOrgsRequest instantiates a new DelinkChildOrgsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDelinkChildOrgsRequest(orgIds []string) *DelinkChildOrgsRequest {
	this := DelinkChildOrgsRequest{}
	this.OrgIds = orgIds
	return &this
}

// NewDelinkChildOrgsRequestWithDefaults instantiates a new DelinkChildOrgsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDelinkChildOrgsRequestWithDefaults() *DelinkChildOrgsRequest {
	this := DelinkChildOrgsRequest{}
	return &this
}

// GetOrgIds returns the OrgIds field value
func (o *DelinkChildOrgsRequest) GetOrgIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.OrgIds
}

// GetOrgIdsOk returns a tuple with the OrgIds field value
// and a boolean to check if the value has been set.
func (o *DelinkChildOrgsRequest) GetOrgIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrgIds, true
}

// SetOrgIds sets field value
func (o *DelinkChildOrgsRequest) SetOrgIds(v []string) {
	o.OrgIds = v
}

func (o DelinkChildOrgsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DelinkChildOrgsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["orgIds"] = o.OrgIds
	return toSerialize, nil
}

func (o *DelinkChildOrgsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"orgIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDelinkChildOrgsRequest := _DelinkChildOrgsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDelinkChildOrgsRequest)

	if err != nil {
		return err
	}

	*o = DelinkChildOrgsRequest(varDelinkChildOrgsRequest)

	return err
}

type NullableDelinkChildOrgsRequest struct {
	value *DelinkChildOrgsRequest
	isSet bool
}

func (v NullableDelinkChildOrgsRequest) Get() *DelinkChildOrgsRequest {
	return v.value
}

func (v *NullableDelinkChildOrgsRequest) Set(val *DelinkChildOrgsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDelinkChildOrgsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDelinkChildOrgsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDelinkChildOrgsRequest(val *DelinkChildOrgsRequest) *NullableDelinkChildOrgsRequest {
	return &NullableDelinkChildOrgsRequest{value: val, isSet: true}
}

func (v NullableDelinkChildOrgsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDelinkChildOrgsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


